(define-module (cig-admin)
  #:use-module (guix build-system cargo)
  #:use-module (guix build-system cmake)
  #:use-module (guix build-system emacs)
  #:use-module (guix build-system glib-or-gtk)
  #:use-module (guix build-system gnu)
  #:use-module (guix build-system go)
  #:use-module (guix build-system meson)
  #:use-module (guix build-system perl)
  #:use-module (guix build-system python)
  #:use-module (guix build-system pyproject)
  #:use-module (guix build-system qt)
  #:use-module (guix build-system ruby)
  #:use-module (guix build-system trivial)
  #:use-module (guix download)
  #:use-module (guix git-download)
  #:use-module (guix gexp)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix packages)
  #:use-module (guix utils)
  #:use-module (gnu packages)
  #:use-module (gnu packages acl)
  #:use-module (gnu packages algebra)
  #:use-module (gnu packages attr)
  #:use-module (gnu packages autotools)
  #:use-module (gnu packages backup)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages bison)
  #:use-module (gnu packages boost)
  #:use-module (gnu packages bootloaders)
  #:use-module (gnu packages c)
  #:use-module (gnu packages check)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages crates-graphics)
  #:use-module (gnu packages crates-io)
  #:use-module (gnu packages crypto)
  #:use-module (gnu packages cryptsetup)
  #:use-module (gnu packages curl)
  #:use-module (gnu packages cyrus-sasl)
  #:use-module (gnu packages datastructures)
  #:use-module (gnu packages disk)
  #:use-module (gnu packages dns)
  #:use-module (gnu packages elf)
  #:use-module (gnu packages file)
  #:use-module (gnu packages flex)
  #:use-module (gnu packages fonts)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages gawk)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages gl)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages gnupg)
  #:use-module (gnu packages golang)
  #:use-module (gnu packages groff)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages guile)
  #:use-module (gnu packages guile-xyz)
  #:use-module (gnu packages image)
  #:use-module (gnu packages imagemagick)
  #:use-module (gnu packages inkscape)
  #:use-module (gnu packages kerberos)
  #:use-module (gnu packages libbsd)
  #:use-module (gnu packages libunwind)
  #:use-module (gnu packages libusb)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages lua)
  #:use-module (gnu packages m4)
  #:use-module (gnu packages mail)
  #:use-module (gnu packages man)
  #:use-module (gnu packages mcrypt)
  #:use-module (gnu packages mpi)
  #:use-module (gnu packages ncurses)
  #:use-module (gnu packages networking)
  #:use-module (gnu packages openldap)
  #:use-module (gnu packages package-management)
  #:use-module (gnu packages patchutils)
  #:use-module (gnu packages pciutils)
  #:use-module (gnu packages pcre)
  #:use-module (gnu packages perl)
  #:use-module (gnu packages perl-check)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages polkit)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-build)
  #:use-module (gnu packages python-crypto)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages qt)
  #:use-module (gnu packages readline)
  #:use-module (gnu packages ruby)
  #:use-module (gnu packages selinux)
  #:use-module (gnu packages serialization)
  #:use-module (gnu packages sqlite)
  #:use-module (gnu packages ssh)
  #:use-module (gnu packages sphinx)
  #:use-module (gnu packages tcl)
  #:use-module (gnu packages terminals)
  #:use-module (gnu packages texinfo)
  #:use-module (gnu packages textutils)
  #:use-module (gnu packages time)
  #:use-module (gnu packages tls)
  #:use-module (gnu packages version-control)
  #:use-module (gnu packages web)
  #:use-module (gnu packages xdisorg)
  #:use-module (gnu packages xml)
  #:use-module (gnu packages xorg))

(define-public woeusb
  (let ((revision "0")
        ;; named branch is outdated
        (commit "34b400d99d3c4089f487e1d4f7d71970b2d4429e"))
    (package
     (name "woeusb")
     (version (git-version "0.0.0" revision commit))
     (source
      (origin
       (method git-fetch)
       (uri (git-reference
	     (url "https://github.com/WoeUSB/WoeUSB.git")
	     (commit commit)))
       (file-name (git-file-name name version))
       (sha256
	(base32 "05ghja2rpn4kqak9yll398na54dscsfnm3z5f2pi54lan98wzimh"))))
     (build-system trivial-build-system)
     (inputs
      (list ntfs-3g grub ncurses parted coreutils util-linux wimlib))
     (arguments
      `(#:modules ((guix build utils))
        #:builder
        (begin
          (use-modules (guix build utils))
          ;; copy source
          (copy-recursively (assoc-ref %build-inputs "source") ".")
          ;; patch source
          (substitute* "sbin/woeusb"
		       (("tput sgr0") (string-append (assoc-ref %build-inputs "ncurses")
						     "/bin/tput"
						     " sgr0"))
		       (("parted --script")
			(string-append (assoc-ref %build-inputs "parted")
				       "/sbin/parted --script"))
		       (("parted \\\\")
			(string-append (assoc-ref %build-inputs "parted")
				       "/sbin/parted \\"))
		       (("grub-install") (string-append (assoc-ref %build-inputs "grub")
							"/sbin/grub-install"))
		       (("command -v mkntfs") (string-append
					       "command -v "
					       (assoc-ref %build-inputs "ntfs-3g")
					       "/sbin/mkntfs"))
		       (("command_mkntfs_ref=mkntfs") (string-append
						       "command_mkntfs_ref="
						       (assoc-ref %build-inputs "ntfs-3g")
						       "/sbin/mkntfs"))
		       (("readlink \\\\") (string-append
					   (assoc-ref %build-inputs "coreutils")
					   "/bin/readlink \\"))
		       (("wimlib-imagex") (string-append
					   (assoc-ref %build-inputs "wimlib")
					   "/bin/wimlib-imagex"))
		       ;; could not find partprobe package
		       ;; as i see this command never used in the program
		       (("partprobe \\\\") "\\"))
          ;; install phase
          (install-file "sbin/woeusb" (string-append %output "/bin"))
          #t)))
     (home-page "https://github.com/WoeUSB/WoeUSB")
     (synopsis "A Microsoft Windows® USB installation media preparer for GNU+Linux")
     (description "Very usefull package for anyone who wants to make a bootable Windows® USB stick
using free and open source operating system.")
     (license license:gpl3+))))
